# Generated by Django 4.1.4 on 2022-12-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_alter_link_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.FilePathField(path='C:/Users/ulugbek/Downloads/MEDICAL CHEMISTRY - DENTESTRY (UZB)'),
        ),
    ]
